@startuml

left to right direction 
skinparam usecase{
    BackgroundColor yellow
}
actor customer 
actor technician 
actor bank 

rectangle "atm system" {
customer --> (check balance) : <<include>>
customer --> (deposit)
customer --> (repair)
technician --> (maintain)
(check balance) <-- bank 
(maintain) <-- bank 

}
(check balance)#blue 
(deposit)#green
customer#green
@enduml

